<?php
$plugin_root = isset( $argv[1] ) ? rtrim( $argv[1], '/\\' ) : '';
if ( '' === $plugin_root || ! is_dir( $plugin_root ) ) { fwrite( STDERR, 'usage: php local-form-rate-smoke.php /path/to/plugin\n' ); exit(64); }
define('ABSPATH',__DIR__.'/');define('MINUTE_IN_SECONDS',60);$GLOBALS['filters']=array();$GLOBALS['transients']=array();
function add_filter($t,$c,$p=10,$a=1){$GLOBALS['filters'][$t][$p][]=$c;}function apply_filters($t,$v){if(empty($GLOBALS['filters'][$t]))return$v;ksort($GLOBALS['filters'][$t]);foreach($GLOBALS['filters'][$t] as$cbs)foreach($cbs as$cb)$v=$cb($v);return$v;}function add_action(){}
function sanitize_key($v){return preg_replace('/[^a-z0-9_\-]/','',strtolower((string)$v));}function sanitize_text_field($v){return trim(strip_tags((string)$v));}function sanitize_email($v){return filter_var(trim($v),FILTER_SANITIZE_EMAIL);}function is_email($v){return false!==filter_var($v,FILTER_VALIDATE_EMAIL);}function wp_unslash($v){return$v;}function wp_salt($x='auth'){return'fixed';}function get_transient($k){return$GLOBALS['transients'][$k]??false;}function set_transient($k,$v,$ttl){$GLOBALS['transients'][$k]=$v;return true;}function home_url($p='/'){return'https://fasdent.ir'.$p;}function wp_parse_url($u,$c=-1){return parse_url($u,$c);}function is_wp_error($v){return$v instanceof WP_Error;}class WP_Error{function __construct($c,$m){}}function current_datetime(){return new DateTimeImmutable('2026-08-14 17:00:30',new DateTimeZone('Asia/Tehran'));}function wp_timezone_string(){return'Asia/Tehran';}function alipasandi_clinic_option($k){return'';}function alipasandi_parse_opening_hours($r){return array('errors'=>array(),'schedule'=>array());}function alipasandi_booking_now(){return current_datetime();}function alipasandi_booking_min_lead_minutes(){return 0;}function alipasandi_booking_horizon_days(){return 365;}function alipasandi_service_registry_issues(){return array();}function alipasandi_allowed_services(){return array();}function alipasandi_normalize_digits($v){return$v;}function alipasandi_email_matches_home_domain(){return true;}function wp_get_referer(){return false;}function get_page_by_path(){return null;}function wp_safe_redirect(){}function add_query_arg($k,$v,$u){return$u;}function admin_url($p=''){return$p;}function wp_verify_nonce(){return true;}function sanitize_textarea_field($v){return$v;}function esc_html($v){return$v;}function wp_mail(){return true;}
require $plugin_root . '/includes/forms.php';
$P=0;$F=0;function t($n,$ok,$d=''){global$P,$F;$ok?$P++:$F++;echo($ok?'PASS':'FAIL'),"\t$n\t$d\n";}
$_SERVER['REMOTE_ADDR']='203.0.113.10';
for($i=1;$i<=5;$i++){t('precheck_'.$i,'valid'===alipasandi_form_rate_limit_status('alipasandi_contact'));alipasandi_form_rate_limit_consume('alipasandi_contact');}
t('sixth_limited','rate_limited'===alipasandi_form_rate_limit_status('alipasandi_contact'));t('appointment_separate','valid'===alipasandi_form_rate_limit_status('alipasandi_appointment'));
$keys=array_keys($GLOBALS['transients']);t('raw_ip_not_key',!array_filter($keys,fn($k)=>str_contains($k,'203.0.113.10')),implode(',',$keys));t('values_counter_only',!array_filter($GLOBALS['transients'],fn($v)=>!is_int($v)));
# Simulate mail failure policy: precheck alone never consumes.
$GLOBALS['transients']=array();t('mail_failure_precheck_valid','valid'===alipasandi_form_rate_limit_status('alipasandi_contact'));t('mail_failure_not_consumed',empty($GLOBALS['transients']));
$_SERVER['REMOTE_ADDR']='bad';$before=count($GLOBALS['transients']);t('invalid_ip_fail_closed','unavailable'===alipasandi_form_rate_limit_status('alipasandi_contact'));t('invalid_ip_no_counter',$before===count($GLOBALS['transients']));
echo"SUMMARY\tPASS=$P\tFAIL=$F\tPHP=".PHP_VERSION."\n";exit($F?1:0);
